name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the covid-19-di-poc repo.  Please check out the Wiki for initial informationa and resources'
        pr-message: 'Congrats for your first pull request from the covid-di team leads!  We hope it''s the first of many!'
